#!/usr/bin/env bash
# Bootstrap everything the BabbleSim split-latency simulation needs, without
# root. Idempotent: safe to re-run.
#
# It assumes scripts/sim/bootstrap.sh has already created .sim/venv and
# .sim/ws (the west workspace with zmk + zephyr), and adds:
#
#   .sim/tools/i386-multilib   32-bit glibc/libgcc unpacked from Debian .debs
#   .sim/tools/bsim-bin/gcc    gcc wrapper that makes `gcc -m32` work with it
#   .sim/bsim/components/*     the BabbleSim components (base + ext_*)
#   .sim/bsim/nrf_hw_models    the nRF HW models Zephyr module
#   .sim/bsim/{bin,lib}        the built simulator (bs_2G4_phy_v1, libs)
#
# Why the multilib dance: zephyr/boards/native/nrf_bsim/CMakeLists.txt links
# the BabbleSim libraries as libUtilv1.32.a etc., i.e. the nrf52_bsim board is
# 32-bit x86 only, and this host has no gcc multilib and no sudo/apt install.
#
# Usage: scripts/bsim/bootstrap.sh [--skip-fetch] [--skip-build]
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
SIM_DIR="${SIM_DIR:-$REPO_ROOT/.sim}"
TOOLS_DIR="$SIM_DIR/tools"
MULTILIB_DIR="$TOOLS_DIR/i386-multilib"
WRAPPER_DIR="$TOOLS_DIR/bsim-bin"
BSIM_DIR="${BSIM_OUT_PATH:-$SIM_DIR/bsim}"
COMPONENTS_DIR="$BSIM_DIR/components"
JOBS="${JOBS:-$(nproc)}"

skip_fetch=0
skip_build=0
while [[ $# -gt 0 ]]; do
    case "$1" in
        --skip-fetch) skip_fetch=1 ;;
        --skip-build) skip_build=1 ;;
        -h|--help) sed -n '2,/^set -euo/p' "${BASH_SOURCE[0]}" | grep -v '^set -euo' | sed 's/^# \{0,1\}//'; exit 0 ;;
        *) echo "unknown option: $1" >&2; exit 2 ;;
    esac
    shift
done

log() { printf '\033[1;34m[bsim-bootstrap]\033[0m %s\n' "$*"; }

# --- 1. 32-bit C library and libgcc (no root) ------------------------------
# Revisions must match the host compiler/glibc; `apt-get download` needs no
# root and resolves the exact versions from the already-present apt indexes.
if [[ ! -f "$MULTILIB_DIR/usr/lib32/crt1.o" ]]; then
    log "downloading 32-bit runtime/dev packages"
    tmp="$(mktemp -d)"
    trap 'rm -rf "$tmp"' EXIT
    gcc_major="$(gcc -dumpversion | cut -d. -f1)"
    (cd "$tmp" && apt-get download libc6-i386 libc6-dev-i386 lib32gcc-s1 "lib32gcc-${gcc_major}-dev")
    mkdir -p "$MULTILIB_DIR"
    for deb in "$tmp"/*.deb; do dpkg-deb -x "$deb" "$MULTILIB_DIR"; done
    # /usr/lib32/libc.so is a linker script with absolute /lib32 and /lib paths;
    # `-Wl,--sysroot=` makes ld resolve them inside this tree, which needs the
    # merged-usr symlinks Debian has at the real root.
    ln -sfn usr/lib32 "$MULTILIB_DIR/lib32"
    mkdir -p "$MULTILIB_DIR/lib"
    ln -sfn ../usr/lib32/ld-linux.so.2 "$MULTILIB_DIR/lib/ld-linux.so.2"
    log "unpacked into $MULTILIB_DIR"
else
    log "32-bit multilib already unpacked"
fi

# --- 2. gcc wrapper --------------------------------------------------------
mkdir -p "$WRAPPER_DIR"
gcc_major="$(gcc -dumpversion | cut -d. -f1)"
cat > "$WRAPPER_DIR/gcc" <<EOF
#!/bin/sh
# 32-bit-capable gcc wrapper for the BabbleSim / nrf52_bsim builds.
# Generated by scripts/bsim/bootstrap.sh -- do not edit by hand.
#
# gcc -m32 on this host fails ("cannot find Scrt1.o", "cannot find -lgcc"):
# there is no multilib package installed and no root to install one. The
# needed files are unpacked in ../i386-multilib; this wrapper points gcc at
# them whenever -m32 is on the command line and otherwise execs the real gcc
# unchanged. Two extra include dirs are needed because gcc -m32 searches
# /usr/include/i386-linux-gnu, which does not exist on a Debian amd64 host:
# the bi-arch headers live in /usr/include/x86_64-linux-gnu and only
# gnu/stubs-32.h comes from libc6-dev-i386.
REAL_GCC=\${BSIM_REAL_GCC:-$(command -v gcc)}
SYSROOT=\$(cd "\$(dirname "\$0")/../i386-multilib" && pwd)
for a in "\$@"; do
    if [ "\$a" = "-m32" ]; then
        exec "\$REAL_GCC" \\
            -B"\$SYSROOT/usr/lib/gcc/x86_64-linux-gnu/$gcc_major/" \\
            -B"\$SYSROOT/usr/lib32/" \\
            -L"\$SYSROOT/usr/lib32" \\
            -idirafter "\$SYSROOT/usr/include/x86_64-linux-gnu" \\
            -idirafter /usr/include/x86_64-linux-gnu \\
            -Wl,--sysroot="\$SYSROOT" \\
            -Wl,--dynamic-linker="\$SYSROOT/usr/lib32/ld-linux.so.2" \\
            -Wl,--disable-new-dtags \\
            -Wl,-rpath,"\$SYSROOT/usr/lib32" \\
            "\$@"
    fi
done
exec "\$REAL_GCC" "\$@"
EOF
chmod +x "$WRAPPER_DIR/gcc"
ln -sf gcc "$WRAPPER_DIR/cc"
log "gcc wrapper: $WRAPPER_DIR/gcc"

# --- 3. BabbleSim sources --------------------------------------------------
# Revisions are the ones Zephyr v4.1 pins in its babblesim manifest group
# (`west list -a | grep babblesim` in .sim/ws).
fetch() { # <url> <dir> <rev>
    local url="$1" dir="$2" rev="$3"
    if [[ ! -d "$dir/.git" ]]; then
        log "cloning $(basename "$dir")"
        git clone --quiet --filter=blob:none "$url" "$dir"
    fi
    if [[ "$(git -C "$dir" rev-parse HEAD)" != "$rev" ]]; then
        git -C "$dir" fetch --quiet origin "$rev" || git -C "$dir" fetch --quiet
        git -C "$dir" checkout --quiet "$rev"
    fi
}

if [[ $skip_fetch -eq 0 ]]; then
    mkdir -p "$BSIM_DIR"
    fetch https://github.com/BabbleSim/base                          "$COMPONENTS_DIR"                                  153101c61ce7106f6ba8b108b5c6488efdc1151a
    fetch https://github.com/BabbleSim/ext_2G4_channel_NtNcable      "$COMPONENTS_DIR/ext_2G4_channel_NtNcable"          20a38c997f507b0aa53817aab3d73a462fff7af1
    fetch https://github.com/BabbleSim/ext_2G4_channel_multiatt      "$COMPONENTS_DIR/ext_2G4_channel_multiatt"          bde72a57384dde7a4310bcf3843469401be93074
    fetch https://github.com/BabbleSim/ext_2G4_device_WLAN_actmod    "$COMPONENTS_DIR/ext_2G4_device_WLAN_actmod"        9cb6d8e72695f6b785e57443f0629a18069d6ce4
    fetch https://github.com/BabbleSim/ext_2G4_device_burst_interferer "$COMPONENTS_DIR/ext_2G4_device_burst_interferer" 5b5339351d6e6a2368c686c734dc8b2fc65698fc
    fetch https://github.com/BabbleSim/ext_2G4_device_playback       "$COMPONENTS_DIR/ext_2G4_device_playback"           abb48cd71ddd4e2a9022f4bf49b2712524c483e8
    fetch https://github.com/BabbleSim/ext_2G4_libPhyComv1           "$COMPONENTS_DIR/ext_2G4_libPhyComv1"               15ae0f87fa049e04cbec48a866f3bc37d903f950
    fetch https://github.com/BabbleSim/ext_2G4_modem_BLE_simple      "$COMPONENTS_DIR/ext_2G4_modem_BLE_simple"          4d2379de510684cd4b1c3bbbb09bce7b5a20bc1f
    fetch https://github.com/BabbleSim/ext_2G4_modem_magic           "$COMPONENTS_DIR/ext_2G4_modem_magic"               edfcda2d3937a74be0a59d6cd47e0f50183453da
    fetch https://github.com/BabbleSim/ext_2G4_phy_v1                "$COMPONENTS_DIR/ext_2G4_phy_v1"                    62e797b2c518e5bb6123a198382ed2b64b8c068e
    fetch https://github.com/BabbleSim/ext_libCryptov1               "$COMPONENTS_DIR/ext_libCryptov1"                   da246018ebe031e4fe4a8228187fb459e9f3b2fa
    # The nRF peripheral models are a Zephyr module, not a BabbleSim component.
    fetch https://github.com/zephyrproject-rtos/nrf_hw_models        "$BSIM_DIR/nrf_hw_models"                           73a5d5827a94820be65b7d276d28173ec10bab9f
    ln -sfn components/common/Makefile "$BSIM_DIR/Makefile"
fi

# --- 4. build --------------------------------------------------------------
if [[ $skip_build -eq 0 ]]; then
    export PATH="$WRAPPER_DIR:$TOOLS_DIR/bin:$PATH"
    export BSIM_OUT_PATH="$BSIM_DIR"
    export BSIM_COMPONENTS_PATH="$COMPONENTS_DIR"
    log "make everything -j$JOBS (this needs the GNU make built by scripts/sim/bootstrap.sh)"
    make -C "$BSIM_DIR" everything "-j$JOBS"
fi

log "done. bin/: $(ls "$BSIM_DIR/bin" 2>/dev/null | grep -c . || echo 0) files"
log "run the simulation with: scripts/bsim/run.sh"
